#!/bin/bash

# @file cassandra
#
# Project Clearwater - IMS in the Cloud
# Copyright (C) 2013  Metaswitch Networks Ltd
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version, along with the "Special Exception" for use of
# the program along with SSL, set forth below. This program is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details. You should have received a copy of the GNU General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
# The author can be reached by email at clearwater@metaswitch.com or by
# post at Metaswitch Networks Ltd, 100 Church St, Enfield EN2 6BQ, UK
#
# Special Exception
# Metaswitch Networks Ltd  grants you permission to copy, modify,
# propagate, and distribute a work formed by combining OpenSSL with The
# Software, or a work derivative of such a combination, even if such
# copying, modification, propagation, or distribution would otherwise
# violate the terms of the GPL. You must comply with the GPL in all
# respects for all of the code used other than OpenSSL.
# "OpenSSL" means OpenSSL toolkit software distributed by the OpenSSL
# Project and licensed under the OpenSSL Licenses, or a work based on such
# software and licensed under the OpenSSL Licenses.
# "OpenSSL Licenses" means the OpenSSL License and Original SSLeay License
# under which the OpenSSL Project distributes the OpenSSL toolkit software,
# as those licenses appear in the file LICENSE-OPENSSL.

. /etc/clearwater/config

TEMPLATE_IPV4_SECTION=""
TEMPLATE_HEAPSIZE_SECTION=""

TEMPLATE_FILE=/usr/share/clearwater/cassandra/cassandra-env.sh.template
new_file=$(mktemp)

# If we're using IPv6 addresses we shouldn't tell the JVM to prefer
# IPv4 addresses (otherwise cassandra won't be able to start). This is
# controlled via the preferIPv4Stack option in cassandra-env.sh.

if ! /usr/share/clearwater/bin/is-address-ipv6 $local_ip
then
  TEMPLATE_IPV4_SECTION='JVM_OPTS="$JVM_OPTS -Djava.net.preferIPv4Stack=true"'
fi

# On AIO nodes and in containers, we want to restrict Cassandra's memory usage,
# as the system is shared with more processes, and Cassandra's approach of
# using 70% of RAM isn't appropriate.

if [[ $reduce_cassandra_mem_usage = "Y" ]]
then
  TEMPLATE_HEAPSIZE_SECTION="MAX_HEAP_SIZE=\"512M\"\nHEAP_NEWSIZE=\"128M\""
fi

cat $TEMPLATE_FILE |\
  sed "s/<<<TEMPLATE_IPV4_SECTION>>>/$TEMPLATE_IPV4_SECTION/" |\
  sed "s/<<<TEMPLATE_HEAPSIZE_SECTION>>>/$TEMPLATE_HEAPSIZE_SECTION/"\
  > $new_file

if [[ -e /etc/cassandra/cassandra-env.sh &&
  "$(md5sum < /etc/cassandra/cassandra-env.sh)" = "$(md5sum < $new_file)" ]]
then
  # File unchanged, do nothing
  /bin/true
else
  rm -f /etc/cassandra/cassandra-env.sh
  cp $new_file /etc/cassandra/cassandra-env.sh
  # File has changed, need to restart cassandra to pick up the change.
  service cassandra stop
fi

chmod 0755 /etc/cassandra/cassandra-env.sh
rm $new_file
