#!/bin/sh

set -e

case "$1" in
  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
  remove|purge)
    # Remove the boostrapping state flags created by the cassandra etcd plugin:
    rm -f /etc/cassandra/cassandra_bootstrap_in_progress
    rm -f /etc/cassandra/cassandra_bootstrapped
    ;;
  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
